# Generated by Django 5.2.8 on 2026-07-09 14:41

import django.db.models.deletion
import django_lifecycle.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroCirculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('online', 'Online'), ('ocupado', 'Ocupado'), ('offline', 'Offline')], default='offline', max_length=20, verbose_name='Status')),
                ('eh_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulos_onde_apareco', to=settings.AUTH_USER_MODEL, verbose_name='Contato')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_circulo', to=settings.AUTH_USER_MODEL, verbose_name='Dono do círculo')),
            ],
            options={
                'verbose_name': 'Membro do círculo',
                'verbose_name_plural': 'Membros do círculo',
                'ordering': ['-status', 'contato__name'],
                'constraints': [models.UniqueConstraint(fields=('dono', 'contato'), name='membro_circulo_unico')],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
