# Generated by Django 5.2.8 on 2026-07-09 14:54

import django.db.models.deletion
import django_lifecycle.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buzina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('atendida', 'Atendida'), ('recusada', 'Recusada'), ('respondida', 'Respondida')], default='pendente', max_length=20, verbose_name='Status')),
                ('resposta_rapida', models.CharField(blank=True, choices=[('ja_vou', 'Já vou'), ('ocupado', 'Tô ocupado'), ('ligo_depois', 'Ligo em 5 min')], max_length=20, null=True, verbose_name='Resposta rápida')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzinas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzinas_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Buzina',
                'verbose_name_plural': 'Buzinas',
                'ordering': ['-created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
