# Generated by Django 5.2.8 on 2026-07-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_buzina'),
    ]

    operations = [
        migrations.AddField(
            model_name='buzina',
            name='mensagem',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Mensagem'),
        ),
    ]
