# Generated by Django 5.2.8 on 2026-07-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_buzina_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzina',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('atendida', 'Atendida'), ('recusada', 'Recusada'), ('respondida', 'Respondida'), ('cancelada', 'Cancelada'), ('perdida', 'Perdida')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
