# Generated by Django 5.2.8 on 2026-07-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_buzina_status_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='buzina',
            name='lida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lida em'),
        ),
        migrations.AlterField(
            model_name='membrocirculo',
            name='eh_vip',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
    ]
