# Generated by Django 5.2.8 on 2026-07-12 04:56

import django.db.models.deletion
import django_lifecycle.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_convite_circulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convitecirculo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Convite de próximos', 'verbose_name_plural': 'Convites de próximos'},
        ),
        migrations.AlterModelOptions(
            name='membrocirculo',
            options={'ordering': ['-status', 'contato__name'], 'verbose_name': 'Membro dos próximos', 'verbose_name_plural': 'Membros dos próximos'},
        ),
        migrations.AlterField(
            model_name='membrocirculo',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_circulo', to=settings.AUTH_USER_MODEL, verbose_name='Dono dos próximos'),
        ),
        migrations.CreateModel(
            name='CanalPublico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('chave', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Chave pública')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('regenerado_em', models.DateTimeField(blank=True, null=True, verbose_name='Regenerado em')),
                ('proprietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canal_publico', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Canal público',
                'verbose_name_plural': 'Canais públicos',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CutucaoPublico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nickname', models.CharField(blank=True, default='', max_length=40, verbose_name='Nickname')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('dispensado', 'Dispensado')], default='enviado', max_length=20, verbose_name='Status')),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutucoes', to='dashboard.canalpublico', verbose_name='Canal')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutucoes_publicos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutucoes_publicos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remetente autenticado')),
            ],
            options={
                'verbose_name': 'Cutucão público',
                'verbose_name_plural': 'Cutucões públicos',
                'ordering': ['-created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
