# Generated by Django 5.2.8 on 2026-07-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_convitecirculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutucaopublico',
            name='resposta_rapida',
            field=models.CharField(blank=True, choices=[('ja_vou', 'Já vou'), ('ocupado', 'Tô ocupado'), ('ligo_depois', 'Ligo em 5 min')], max_length=20, null=True, verbose_name='Resposta rápida'),
        ),
        migrations.AddField(
            model_name='cutucaopublico',
            name='token_visita',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Token de visita'),
        ),
        migrations.AlterField(
            model_name='cutucaopublico',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('respondida', 'Respondida'), ('atendida', 'Atendida'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada'), ('perdida', 'Perdida')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
