# Generated by Django 5.2.8 on 2026-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_cutucao_publico_migrar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buzina',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='buzina',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='buzina',
            name='precisao_metros',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Precisão (m)'),
        ),
        migrations.AddField(
            model_name='cutucaopublico',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='cutucaopublico',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='cutucaopublico',
            name='precisao_metros',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Precisão (m)'),
        ),
    ]
