/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./templates/**/*.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0b1326',
        'on-background': '#dae2fd',
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#ccc3d8',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: '#958da1',
        'outline-variant': '#4a4455',
        'surface-tint': '#d2bbff',
        primary: '#d2bbff',
        'on-primary': '#3f008e',
        'primary-container': '#7c3aed',
        'on-primary-container': '#ede0ff',
        'inverse-primary': '#732ee4',
        'primary-fixed': '#eaddff',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-primary-fixed-variant': '#5a00c6',
        secondary: '#4cd7f6',
        'on-secondary': '#003640',
        'secondary-container': '#03b5d3',
        'on-secondary-container': '#00424e',
        'secondary-fixed': '#acedff',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary-fixed': '#001f26',
        'on-secondary-fixed-variant': '#004e5c',
        tertiary: '#ffb784',
        'on-tertiary': '#4f2500',
        'tertiary-container': '#a15100',
        'on-tertiary-container': '#ffe0cd',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb784',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#713700',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        unit: '4px',
      },
      fontFamily: {
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'display-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'display-lg-mobile': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"Hanken Grotesk"', 'sans-serif'],
        'label-bold': ['"JetBrains Mono"', 'monospace'],
        'button-text': ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'button-text': ['18px', { lineHeight: '24px', fontWeight: '700' }],
      },
      boxShadow: {
        neumorphic: '4px 4px 10px rgba(0,0,0,0.4), -2px -2px 10px rgba(255,255,255,0.05)',
        'neumorphic-inset': 'inset 4px 4px 10px rgba(0,0,0,0.4), inset -2px -2px 10px rgba(255,255,255,0.05)',
        buzz: '0 0 40px rgba(124, 58, 237, 0.4)',
      },
    },
  },
  plugins: [],
};
