/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./templates/**/*.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#F8F9FA',
        'on-background': '#1A1C1E',
        surface: '#FFFFFF',
        'surface-dim': '#E8EAED',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F1F3F5',
        'surface-container': '#EBEDF0',
        'surface-container-high': '#E3E5E8',
        'surface-container-highest': '#DCDDE1',
        'surface-variant': '#EBEDF0',
        'on-surface': '#1A1C1E',
        'on-surface-variant': '#5C5F66',
        'inverse-surface': '#2F3033',
        'inverse-on-surface': '#F1F3F5',
        outline: '#757780',
        'outline-variant': '#C5C6CE',
        'surface-tint': '#FF6600',
        primary: '#FF6600',
        'on-primary': '#FFFFFF',
        'primary-container': '#FF8533',
        'on-primary-container': '#FFFFFF',
        'inverse-primary': '#FFB380',
        'primary-fixed': '#FFE0CC',
        'primary-fixed-dim': '#FFB380',
        'on-primary-fixed': '#3D1400',
        'on-primary-fixed-variant': '#E65C00',
        secondary: '#8E24AA',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#E1BEE7',
        'on-secondary-container': '#4A148C',
        'secondary-fixed': '#F3E5F5',
        'secondary-fixed-dim': '#CE93D8',
        'on-secondary-fixed': '#4A148C',
        'on-secondary-fixed-variant': '#6A1B9A',
        tertiary: '#E65100',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#FFCCBC',
        'on-tertiary-container': '#BF360C',
        'tertiary-fixed': '#FFE0B2',
        'tertiary-fixed-dim': '#FFB74D',
        'on-tertiary-fixed': '#3E2723',
        'on-tertiary-fixed-variant': '#E65100',
        error: '#B3261E',
        'on-error': '#FFFFFF',
        'error-container': '#F9DEDC',
        'on-error-container': '#410E0B',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        unit: '4px',
      },
      fontFamily: {
        'body-md': ['"Nunito"', 'sans-serif'],
        'body-lg': ['"Nunito"', 'sans-serif'],
        'display-lg': ['"Nunito"', 'sans-serif'],
        'display-lg-mobile': ['"Nunito"', 'sans-serif'],
        'headline-md': ['"Nunito"', 'sans-serif'],
        'label-bold': ['"Nunito"', 'sans-serif'],
        'button-text': ['"Nunito"', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '700' }],
        'button-text': ['18px', { lineHeight: '24px', fontWeight: '700' }],
      },
      boxShadow: {
        cutuca: '0 2px 8px rgba(0, 0, 0, 0.08)',
        'cutuca-lg': '0 8px 24px rgba(0, 0, 0, 0.1)',
        'cutuca-primary': '0 4px 20px rgba(255, 102, 0, 0.35)',
        neumorphic: '0 2px 8px rgba(0, 0, 0, 0.08)',
        'neumorphic-inset': 'inset 0 1px 3px rgba(0, 0, 0, 0.08)',
        buzz: '0 4px 20px rgba(255, 102, 0, 0.35)',
      },
    },
  },
  plugins: [],
};
