"""
Django settings for deep project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
from dj_database_url import parse as dburl
from sentry_sdk.integrations.django import DjangoIntegration
import sentry_sdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_URL = config('BASE_URL', default='http://127.0.0.1:8000')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j&8*f3d)2abrq*vcvto#&gl2(c)7jb%_ee80ncf6ub@$+g(qn0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default=[], cast=Csv())

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS', default='http://*,https://*', cast=Csv()
)

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS', default='http://localhost:8080', cast=Csv()
)

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_filters',
    'storages',
    'hijack',
    'hijack.contrib.admin',
    'anymail',
    'rest_framework',
    'apps.core',
    'apps.dashboard',
    'apps.accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = 'login'

LOGOUT_REDIRECT_URL = 'login'

LOGIN_REDIRECT_URL = 'dashboard:index'

ROOT_URLCONF = 'apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.rota_ativa',
                'apps.dashboard.context_processors.notificacoes',
                'apps.dashboard.context_processors.disponibilidade',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps.wsgi.application'
ASGI_APPLICATION = "apps.routing.application"
DJANGO_SETTINGS_MODULE = config('DJANGO_SETTINGS_MODULE', default='apps.settings')

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

default_dburl = 'sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3')
DATABASES = {
    'default': config('DATABASE_URL', default=default_dburl, cast=dburl),
}

STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.core.utils.CsrfExemptSessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": ('rest_framework.permissions.IsAuthenticated',),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseFormParser',
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
    ),
    "DEFAULT_PAGINATION_CLASS": "apps.core.utils.SimpleAPIPagination",
    "PAGE_SIZE": 15,
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True

# ==================== STATIC & MEDIA FILES CONFIGURATION ====================
DO_SPACES_ACCESS_KEY = config("DO_SPACES_ACCESS_KEY", default="")
DO_SPACES_SECRET_KEY = config("DO_SPACES_SECRET_KEY", default="")
DO_SPACES_BUCKET_NAME = config("DO_SPACES_BUCKET_NAME", default="")
DO_SPACES_REGION = config("DO_SPACES_REGION", default="sfo3")
DO_SPACES_ENDPOINT = config(
    "DO_SPACES_ENDPOINT", default="https://sfo3.digitaloceanspaces.com"
)

if not DEBUG and DO_SPACES_ACCESS_KEY:
    # ========== PRODUÇÃO: Usar Digital Ocean Spaces (S3) ==========

    # AWS S3 Settings (compatível com Digital Ocean Spaces)
    AWS_ACCESS_KEY_ID = DO_SPACES_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY = DO_SPACES_SECRET_KEY
    AWS_STORAGE_BUCKET_NAME = DO_SPACES_BUCKET_NAME
    AWS_S3_REGION_NAME = DO_SPACES_REGION
    AWS_S3_ENDPOINT_URL = DO_SPACES_ENDPOINT

    # S3 Custom Domain (CDN)
    AWS_S3_CUSTOM_DOMAIN = (
        f"{DO_SPACES_BUCKET_NAME}.{DO_SPACES_REGION}.digitaloceanspaces.com"
    )

    # Static files (CSS, JavaScript, Images)
    AWS_LOCATION = "static"
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # Necessário mesmo com S3
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

    # Nova sintaxe do Django 5.x para storages
    STORAGES = {
        "default": {
            "BACKEND": "apps.core.storage_backends.PublicMediaStorage",
        },
        "staticfiles": {
            "BACKEND": "apps.core.storage_backends.StaticStorage",
        },
        "private": {
            "BACKEND": "apps.core.storage_backends.PrivateMediaStorage",
        },
    }

    # Media files (uploads)
    PUBLIC_MEDIA_LOCATION = "media"
    PRIVATE_MEDIA_LOCATION = "private"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/"

    # S3 Object Parameters
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",  # Cache por 24 horas
    }

    # Configurações de segurança
    AWS_DEFAULT_ACL = "public-read"  # Tornar arquivos públicos por padrão
    AWS_S3_FILE_OVERWRITE = False  # Não sobrescrever arquivos com mesmo nome
    AWS_QUERYSTRING_AUTH = False  # Não adicionar tokens de autenticação nas URLs

else:
    # ========== DESENVOLVIMENTO: Usar armazenamento local ==========

    # Static files (CSS, JavaScript, Images)
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

    # Media files (uploads)
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    # Private media (local fallback)
    PRIVATE_MEDIA_LOCATION = "private"
    PRIVATE_MEDIA_ROOT = os.path.join(BASE_DIR, "private_media")

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
        "private": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": PRIVATE_MEDIA_ROOT,
                "base_url": "/private-media/",
            },
        },
    }

ENVIROMENT = config('ENVIROMENT', default='production', cast=str)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'


AUTHENTICATION_BACKENDS = [
    "apps.accounts.backends.EmailOrUsernameModelBackend",
]

CACHES = {
    "default": {
        "BACKEND": config('CACHE_BACKEND', default='django_redis.cache.RedisCache'),
        "LOCATION": config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [config('REDIS_URL', default='redis://127.0.0.1:6379/1')],
        },
    },
}

# Email Configuration
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="App <suporte@app.com.br>")

ANYMAIL = {
    "MAILGUN_API_KEY": config("MAILGUN_API_KEY", default=""),
    "MAILGUN_SENDER_DOMAIN": config("MAILGUN_SENDER_DOMAIN", default=""),
}

HIJACK_LOGIN_REDIRECT_URL = "/"
HIJACK_LOGOUT_REDIRECT_URL = "/admin/"

# ==================== SENTRY CONFIGURATION ====================
SENTRY_DSN = config("SENTRY_DSN", default=None)

if SENTRY_DSN and not DEBUG:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Set traces_sample_rate to 0.1 to capture 100%
        # of transactions for performance monitoring.
        traces_sample_rate=0.1,
        # Set profiles_sample_rate to 0.1 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=0.1,
    )

OPENAI_API_KEY = config("OPENAI_API_KEY", default="")
